#version 460
#extension GL_EXT_ray_tracing : require

struct RayPayload {
	float hitDistance;
	uint originNodeId;
};
layout(location = 0) rayPayloadInEXT RayPayload payload;

layout(std430, binding = 2, set = 0) readonly buffer AdjacencyList { uint neighbors[]; };
layout(std430, binding = 3, set = 0) readonly buffer AdjOffsets  { uint offsets[]; };
layout(std430, binding = 4, set = 0) readonly buffer AdjCounts   { uint edge_counts[]; };

void main() {
	uint hitNodeId = gl_InstanceCustomIndexEXT;
	uint originId = payload.originNodeId;

	if (hitNodeId == originId) {
		ignoreIntersectionEXT;
		return;
	}

	uint start_idx = offsets[originId];
	uint count = edge_counts[originId];

	for (uint i = 0; i < count; i++) {
		if (neighbors[start_idx + i] == hitNodeId) {
			ignoreIntersectionEXT;
			return;
		}
	}
}