#version 450
#extension GL_EXT_shader_atomic_float : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Edge {
	uint nodeA;
	uint nodeB;
};

layout(std430, binding = 0, set = 0) readonly buffer PhysicsBuffer {
	vec4 positions[];
};

layout(std430, binding = 1, set = 0) readonly buffer EdgeList {
	Edge edges[];
};

layout(std430, binding = 2, set = 0) buffer GlobalStress {
	float total_stress;
};

layout(push_constant) uniform SimParams {
	float ideal_length;
	uint edge_count;
} params;

void main() {
	uint id = gl_GlobalInvocationID.x;
	if (id >= params.edge_count) return;

	uint nA = edges[id].nodeA;
	uint nB = edges[id].nodeB;

	vec3 posA = positions[nA].xyz;
	vec3 posB = positions[nB].xyz;

	float current_length = length(posA - posB);
	float diff = current_length - params.ideal_length;

	float local_stress = diff * diff;

	atomicAdd(total_stress, local_stress);
}
