#version 460
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct NodeData {
	vec4 pos;
};

layout(std430, binding = 0) readonly buffer NodeBuffer {
	NodeData nodes[];
};

layout(std430, binding = 5) buffer InstanceBuffer {
	vec4 instance_data[];
};

layout(push_constant) uniform PC {
	float KP;
	float CRK;
	float p;
	float step_size;
	uint vertex_count;
	uint edge_count;
	float R;
}
pc;

void main()
{
	uint i = gl_GlobalInvocationID.x;
	if (i >= pc.vertex_count)
		return;

	vec3 pos = nodes[i].pos.xyz;

	instance_data[i * 4 + 0] = vec4(1.0, 0.0, 0.0, pos.x);
	instance_data[i * 4 + 1] = vec4(0.0, 1.0, 0.0, pos.y);
	instance_data[i * 4 + 2] = vec4(0.0, 0.0, 1.0, pos.z);
}
