name: C/C++ AppImage

on:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            libvulkan-dev \
            libglfw3-dev \
            libcglm-dev \
            libomp-dev \
            glslang-tools \
            libopenxr-dev \
            libfuse2 \
            python3-pip
          sudo pip3 install appimage-builder

      - name: Build patched igraph
        run: |
          git clone https://github.com/leuc/igraph
          cd igraph
          git checkout testing
          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=local_install \
            -DIGRAPH_ENABLE_TLS=ON \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --parallel $(nproc) --target install

      - name: Configure igraph-vlk
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -Digraph_ROOT=$(pwd)/../igraph/local_install/

      - name: Build igraph-vlk
        run: cmake --build build --parallel $(nproc)

      - name: Build AppDir
        run: cmake --build build --target appdir

      - name: Build AppImage
        run: appimage-builder --appdir build/AppDir/ --skip-build --skip-tests

      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: "*.AppImage"
